name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}      

    - name: Build the Docker image
      run: docker build --build-arg SECRET_KEY=${{secrets.SECRET_KEY}} --build-arg DB_HOST=${{secrets.DB_HOST}} --build-arg DB_USER=${{secrets.DB_USER}} --build-arg DB_PASSWORD=${{secrets.DB_PASSWORD}} --build-arg MONGO_URI=${{secrets.MONGO_URI}} -t tripmate .

    - name: taging
      run: docker tag tripmate:latest ${{ secrets.DOCKERHUB_USERNAME }}/tripmate:latest

    - name: Push to Dockerhub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tripmate:latest
    
  deploy:

    runs-on: self-hosted
    needs: build

    steps:
    - name: Pull Docker image
      run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tripmate:latest
    - name: Delete Old docker container
      run: sudo docker rm -f tripmate-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name tripmate-container ${{ secrets.DOCKERHUB_USERNAME }}/tripmate